project:
  type: website
  output-dir: docs

website:
  title: "Samantha Nauman's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - CV.qmd
      - Projects.qmd
      

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

