---
title: "Resume"
author: "Samantha Nauman"
---

**ECOSYSTEM SCIENCE \| SUSTAINABILITY \| WATERSHED SCIENCE**

**SKILLS**

● Snowfall/Snow Hydrology Trend Analysis

● Data Analysis (Excel, RStudio, ArcGIS)

● Population Analysis and Management

● Streamflow Data Application

**EDUCATION**

**Bachelor of Science in Ecosystem Science and Sustainability**

***Minor:*** **Watershed Science**

**August 2022 - May 2026**

**Professional Science Master's in Ecosystem Science and Sustainability - *Water Resources***

**Expected May 2027**

***GPA:*** **3.93**

Colorado State University (CSU), Fort Collins, Colorado

**ACADEMIC EXPERIENCE**

**Honors Thesis - HONR499 Fall 2025**

● Wrote and presented a research proposal on beaver dam analogs to restore the post-fire watershed of Little Beaver Creek following the Cameron Peak Fire in Colorado.

**Limnology - ESS474** **Fall 2024**

● Collected and developed data from Horsetooth Reservoir, using R-programming to compile the data and analyze the water quality and ecosystem within the reservoir.

**HONORS & AWARDS**

● **Member of the University Honors Program**, Colorado State University **August 2022 - Present**

● **Warner College Dean’s List**, Colorado State University **Fall 2022 - Fall 2025**

**LICENSES & CERTIFICATIONS**

**● Social/Humanistic/Behavioral Research (IRB Certification)**, CITI Program

**February 2025 - February 2028**

**● Project WET - Foundations of Water Education,** Colorado Water Center

**November 2025**

**EXPERIENCE**

**Natural Resource Ecology Laboratory, CSU -** *Independent Study Research Assistant* \| *Snow Hydrology Lab* **January 2026 - May 2026**

● Aided in research on finding ways to improve estimations of snow water equivalent (SWE) estimates using snow depth and an analysis of observed density to improve snowpack bulk density.

● Presented findings at the AGU Hydrology Days conference, Carbon Utilization Research Council (CURC), and the Eastern-Western Snow Conference.

**School of Global Environmental Sustainability, CSU** *- Front Desk Coordinator* **January 2024 - Present**

● Ensures smooth daily operations, prioritizing cleanliness and prompt communication.

● Orchestrated setups for SoGES events, ensuring seamless logistics and client satisfaction.

**Aurora Water Department, Aurora, CO** - *Water Conservation Intern \| Horticulture Assistant* **May 2024 - August 2024**

● Worked on landscape maintenance in a water-conservative way, practiced installing and repairing irrigation systems, and compiled data within the water-wise garden from past and present studies performed.

● Educated garden visitors on water-wise principles and Aurora's water conservation programs and assisted in facilitating volunteer work projects.

**VOLUNTEER EXPERIENCE**

**Animal Friends Alliance, Fort Collins, CO** *- Dog Care & Walking* **September 2022 - May 2023**

● Learned to care for and understand the body language of animals with non-verbal communication skills.
